#ifndef VOR3D_MAIN_H
#define VOR3D_MAIN_H

#include "vdiagram.h"

/* If f_radius_poiss returns NAN, then a single seed (bp vertex centroid) is created,
 * so the single resulting voronoi cell is the bp. */

/* A single attempt is made; check vdiagram_is_valid on the result to find out
 * whether it succeeded. No retries, no TOL/EPS_DEG escalation. */

// Copy of seeds inside s_vdiagram
// out_kept_idx, if non-NULL, must point to an array of seeds->N ints; on
// return, out_kept_idx[i] is the index of input seed i inside the returned
// s_vdiagram's seeds/vcells, or -1 if that seed was dropped (e.g. it was not
// strictly interior to the boundary).
//
// vor3d_inside_bp takes a pre-built s_bpoly -- use this when calling
// repeatedly against the same boundary (e.g. growing a tree one bifurcation
// at a time), to build the bpoly once and amortize that cost across calls.
// vor3d_inside_convh is the one-shot convenience wrapper: it builds the
// bpoly from convh on every call and frees it before returning.
s_vdiagram vor3d_inside_bp(const s_points *seeds, const s_bpoly *bp, double vol_max_rel_diff,
                          double EPS_DEG, double TOL, int (*randint)(void*, int),
                          void *rctx, s_dynarray *buff_points, int *out_kept_idx);

s_vdiagram vor3d_inside_convh(const s_points *seeds, const s_convh *convh, double vol_max_rel_diff,
                              double EPS_DEG, double TOL, int (*randint)(void*, int),
                              void *rctx, s_dynarray *buff_points, int *out_kept_idx);

// Seeds generated by Poisson disc sampling
s_vdiagram vor3d_inside_bp_PDS(double (*f_radius_poiss)(double*, void*), void *f_params,
                             const s_bpoly *bp, double vol_max_rel_diff,
                             double EPS_DEG, double TOL,
                             int (*randint)(void*, int), double (*randd01)(void*), void *rctx,
                             s_dynarray *buff_points);
                             // Deep copy of bp inside


#endif
