#ifndef VOR3D_MAIN_H
#define VOR3D_MAIN_H

#include "vdiagram.h"
#include "bpoly.h"


s_vdiagram *vor3d_from_txt(double **seeds, int Ns, char *file_bounding_polyhedron, int max_tries);
s_vdiagram *vor3d_from_bp(double **seeds, int Ns, s_bound_poly *bp, int max_tries);

// Seeds generated by Poisson disc sampling
s_vdiagram *vor3d_from_txt_PDS(double (*f_radius_poiss)(double *), char *file_bounding_polyhedron, int max_tries);
s_vdiagram *vor3d_from_bp_PDS(double (*f_radius_poiss)(double *), s_bound_poly *bp, int max_tries);


// BPOLY.C
extern void generate_file_cube_bp(const char *filename, double length);
extern void generate_file_tetrahedron_bp(const char *filename, double length);
extern void generate_file_sphere_bp(const char *filename, double radius, int nTheta, int nPhi);


// VD_3D.C
extern void clear_volumes_file(char *fname);  // Used for testing output volumes
extern void append_volumes_to_file(s_vdiagram *vdiagram, char *fname, int id);
extern void plot_vdiagram_auto(s_vdiagram *vdiagram, char *f_name, int max_files);

#endif
